volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: ghcr.io/aliakbar-babaei/rocket.chat:latest
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.rocketchat.rule: Host(`${DOMAIN:-}`)
      traefik.http.routers.rocketchat.tls: "true"
      traefik.http.routers.rocketchat.entrypoints: https
      traefik.http.routers.rocketchat.tls.certresolver: le
    env_files:
      - .env
    environment:
      MONGO_URL: mongodb://mongodb:27017/rocketchat
      MONGO_OPLOG_URL: "${MONGO_OPLOG_URL:\
        -mongodb://${MONGODB_ADVERTISED_HOSTNAME:-mongodb}:${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}/\
        local?replicaSet=${MONGODB_REPLICA_SET_NAME:-rs0}}"
      ROOT_URL: ${DOMAIN}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: ${DEPLOY_PLATFORM:-}
      REG_TOKEN: ${REG_TOKEN:-}
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"

  mongodb:
    image: docker.io/bitnami/mongodb:${MONGODB_VERSION:-5.0}
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: ${MONGODB_REPLICA_SET_NAME:-rs0}
      MONGODB_PORT_NUMBER: ${MONGODB_PORT_NUMBER:-27017}
      MONGODB_INITIAL_PRIMARY_HOST: ${MONGODB_INITIAL_PRIMARY_HOST:-mongodb}
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: ${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      MONGODB_ADVERTISED_HOSTNAME: ${MONGODB_ADVERTISED_HOSTNAME:-mongodb}
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}

  nginx:
    image: '${NGINX_IMAGE:-nginx:latest}'
    container_name: '${NGINX_CONTAINER_NAME:-nginx}'
    hostname: '${NGINX_HOSTNAME:-nginx}'
    restart: always
    depends_on:
      - mongodb
      - rocketchat
    volumes:
      - ./nginx/src/conf.d:/etc/nginx/conf.d
      - ./nginx/src/data/:/etc/nginx/data
      - ./nginx/src/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/src/default.conf:/etc/nginx/default.conf
      - ./nginx/var/cache/:/etc/nginx/cache/
      - ./nginx/var/log/:/var/log/nginx/
    ports:
      - '${NGINX_SERVER_HTTP_PORT:-80}:80'
      - '${NGINX_SERVER_HTTPS_PORT:-443}:443'